version: "3.9"
services:
  app:
    build: "."
    container_name: books-front
    restart: "no"        
    volumes:
      - ./:/app
    environment:
      - TZ=America/Sao_Paulo
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    command: sh -c "npm install && npm run dev"
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    expose:
      - ${VITE_PORT}
networks:
  default:
    name: books
    external: true